//! Shared world rules and explicit wire messages. No renderer or network runtime.
pub mod activities;
pub mod admin_commands;
mod airship_landings;
pub mod airships;
pub mod blocks;
pub mod building;
pub mod economy;
pub mod environment;
pub mod forage;
pub mod geography;
pub mod gliders;
pub mod physics;
pub mod poi;
pub mod protocol;
pub mod settlement;
pub mod vehicles;
pub mod village_assets;
pub mod wildlife;
pub mod world;
